config/routes.rb
Nomster::Application.routes.draw do

  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end

  devise_for :users

  resources :users, only: :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    '1*'    => '1_star',
    '2*'   => '2_stars',
    '3*' => '3_stars',
    '4*'  => '4_stars',
    '5*'  => '5_stars',
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true, uniqueness: true, length: {within: 3..50 }
  validates :address, presence: true, length: {minimum: 10 }
  validates :description, presence: true, uniqueness: true, length: {minimum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end


  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photos_params)
    redirect_to place_path(@place)
  end


  private

  def photos_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]

  def index
    @places = Place.paginate(:page => params[:page], :per_page => 4)
  end

  def new
    @place = Place.new
  end



  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
      flash[:error] = "<strong>Could not save</strong> the data you entered is invalid. Please check the fields marked in red."
    end
  end



  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end



  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end
  end



  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end



  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end



  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster by Aleks Gorbenko</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to 'NOMSTER', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to new_place_path do %>
            <i class="glyphicon glyphicon-plus"></i>
            New Place
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href=""><%= current_user.email %></a></li>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="col-xs-6 col-xs-offset-3">
    <% if flash[:error].present? %>
      <div class="alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Place</h1> <br>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, error: 'The name of the place is too short (minimum is 3 characters' %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit 'Update', class: 'btn btn-primary' %>

  <% end %>

</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'slider1.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Bob Bob Ricard
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slider2.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
      Mari Vanna
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slider3.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Eastern European Restaurants
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<% @places.each do |place| %>
<div class="booyah-box col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
  <% if place.photos.present? %>
    <div class="col-xs-6 col-sm-4 col-md-2">
      <%= image_tag place.photos.last.picture, class: 'img-thumbnail' %>
    </div>
  <% end %>

  <h1><%= link_to place.name, place_path(place) %></h1>
  <p class="place-address"><%= place.address %></p>
      <br>
  <p><%= place.description %></p>


  <% if place.comments.present? %>
    <div class="col-xs-12">
      <blockquote class="homepage-comments center-block">
        <% if place.comments.last.humanized_rating.present? %>
          <b><%= place.comments.last.humanized_rating %></b> -
        <% end %>
        <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
          <i class="comment-timestamp"><%= place.comments.last.created_at.strftime("%B %d, %Y") %></i>
      </blockquote>
    </div>
  <% end %>

    <div class="clear"></div>

  <% if place.user.present? %>
    <small class="pull-right added-by">Added by <%= place.user.email %></small>
  <% end %>
</div>
<% end %>


<div class="apple_pagination col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
    <div class="page_info">
      <%= page_entries_info @places %>
    </div>
    <%= will_paginate @places, :container => false %>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1> <br>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit 'Create', class: 'btn btn-primary' %>

  <% end %>

</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= @place.name %></h1>
  <p class="place-address"><%= @place.address %></p>
    <br>

  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap">
    </script>
    <div id="map"></div>
    <% end %>

    <br>
  <div class="col-xs-12 col-sm-7">
    <p class="place-description">"<%= @place.description %>"</p>
  </div>
  <div class="pull-right">
    <!--PHOTOS Button trigger modal -->
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#photoModal">
      Add a Photo
    </button>
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit Place', edit_place_path(@place), class: 'btn btn-default btn-sm' %>
      <%= link_to 'Delete Place', place_path(@place), method: :delete, data: {confirm: "Are you sure you want to delete the following place: '#{@place.name}'?"},class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
    <br>
    <br>

  <div class="col-xs-12">
      <hr>
    <h1 class="pull-left">Photos</h1>

    <div class="clear"></div>
      <br>

    <% if !@place.photos.present? %>
      <i class="absent-item-note">There are currently no photos uploaded for this place.</i>
    <% else %>
      <% @place.photos.each do |photo| %>
        <div class="col-xs-12 col-sm-6 img-responsive">

            <%= image_tag photo.picture, class: 'img-responsive img-rounded' %>

            <p class="text-center photo-caption"><%= photo.caption %></p>
        </div>
      <% end %>
    <% end %>

      <div class="clear"></div>
      <br>
      <hr>

    <h1 class="pull-left">Comments</h1>

    <div class="clear"></div>

    <br>

    <% if !@place.comments.present? %>
      <i class="absent-item-note">There are currently no comments for this place. Be the first to share your experience at <%= @place.name %>!</i>
    <% else %>
      <% @place.comments.each do |comment| %>
        <div class="col-xs-12 col-sm-6">
          <blockquote>
            <% if comment.humanized_rating.present? %>
              <b><%= comment.humanized_rating %></b> -
            <% end %>
            <%= comment.message %>
              <small><%= comment.user.email %></small>
              <br>
              <i class="comment-timestamp"><%= comment.created_at.strftime("%B %d, %Y") %></i>
          </blockquote>
        </div>
      <% end %>
    <% end %>

      <div class="clear"></div>
          <br>

    <!-- COMMENTS Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#commentModal">
      Add a Comment
    </button>
  </div><!-- closing tag for col-xs-12  -->

    <!-- COMMENTS Modal -->
    <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Add Your Comment</h4>
          </div>
          <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
            <div class="modal-body">

              <%= f.input :message %>
                <br>
              <%= f.input :rating, as: :select, collection: Comment::RATINGS %>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Post a Comment", class: 'btn btn-primary btn-sm' %>
            </div>
          <% end%>
        </div>
      </div>
    </div>

    <!-- PHOTO Modal -->
    <div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Add Your Picture</h4>
          </div>
          <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
            <div class="modal-body">

              <%= f.input :picture %>
                <br>
              <%= f.input :caption %>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Submit a Photo", class: 'btn btn-primary btn-sm' %>
            </div>
          <% end%>
        </div>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-xs-12 col-sm-10 col-md-8 col-lg-8 col-sm-offset-1 col-md-offset-2 col-lg-offset-2">

  <div class="col-xs-8 col-xs-offset-2">
    <%= image_tag 'user.png', class: 'center-block profile-pic' %>
  </div>

  <div class="col-xs-12">
    <h1 class="profile-email"><%= @user.email %></h1>
      <br>
    <h3>
      Member since: <%= @user.created_at.strftime("%B %d, %Y") %>
    </h3>
      <br><br>

    <h4>
      <%= @user.comments.count %> total comments
    </h4>
      <br>
    <h4>
      <%= @user.comments.where(rating: '5_stars').count %> total 5* reviews
    </h4>
  </div>

  <div class="clear"></div>

  <br><br><br>

<h2 class="text-center">My Comments</h2>

  <br><br><br>

<% @user.comments.each do |comment| %>
  <div class="col-xs-12 col-sm-6">
    <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <br>
      <i class="comment-timestamp"><%= comment.created_at.strftime("%B %d, %Y") %></i>
    </blockquote>
  </div>
<% end %>

  <div class="clear"></div>

<h2 class="text-center">My Places</h2>

  <br><br><br>

  <% @user.places.each do |place| %>
    <div class="booyah-box col-xs-12 col-lg-10 col-lg-offset-1">
      <% if place.photos.present? %>
        <div class="col-xs-6 col-sm-4 col-md-2">
          <%= image_tag place.photos.last.picture, class: 'img-thumbnail' %>
        </div>
      <% end %>

      <h1><%= link_to place.name, place_path(place) %></h1>
      <p class="place-address"><%= place.address %></p>
        <br>
      <p><%= place.description %></p>
    </div>
  <% end %>
</div>